// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
var staticCacheName = 'travelpal-static-v1';

self.addEventListener('install', function(event) {
	event.waitUntil(
		caches.open(staticCacheName).then(function(cache) {
			return cache.addAll([
			   '/',
		       '/index.html',
		       '/index.html?homescreen=1',
		       '/?homescreen=1',
		       '/images/Forward_Arrow.png',
		       '/styles/main.css',
		       '/styles/notie.css',
		       '/scripts/app.js',
		       '/scripts/db.js',
		       '/scripts/jquery-3.0.0.min.js',
		       '/scripts/main.js',
		       '/scripts/notie.min.js',
			]);
		})
	);
});

self.addEventListener('fetch', function(event) {
 //console.log(event.request.url);
 event.respondWith(
   caches.match(event.request).then(function(response) {
     return response || fetch(event.request);
   })
 );
});